default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: filmes_development
test:
  <<: *default
  database: filmes_test
production:
  primary: &primary_production
    <<: *default
    url: <%= Rails.application.credentials.database_url %>
  cache:
    <<: *primary_production
    database: filmes_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: filmes_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: filmes_production_cable
    migrations_paths: db/cable_migrate
