service: filmes

image: ulysses18/filmes

ssh:
  user: ubuntu

servers:
  - 163.176.59.227

proxy:
  host: filmes.ulysses.dev.br
  app_port: 3000
  ssl: true

registry:
  username: ulysses18
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    DB_HOST: filmes-db
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

aliases:
  console: app exec -i --reuse "bin/rails console"

accessories:
  db:
    image: postgres:16.0
    roles:
      - web
    env:
      clear:
        POSTGRES_DB: filmes_production
        POSTGRES_USER: filmes
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
